### ISSUE TITLE
question about different result of paper v1,v2,v3

### ISSUE THREAD

**Issue by AndyYuan96** [hht1996ok/EA-LSS#6]
Hi, thanks for sharing the great paper, after reading the paper, I'm confused with difference result of different version paper, but the idea looks like don't have too much difference.
For example, in table1, BEVFusion[31] and BEVFusion[31]+EA-BEV, don't have change from paper v1 to v3, but BEVFusion[10] + EA-BEV, change from mAP 70.1 NDS 72.6 to mAP 70.3 NDS 72.6 to mAP 71.2 NDS 73.1，So EA-LSS only work for BEVFusion[10]?
what's more, in table2, BEVFusion[10] + EA-BEV change from mAP 71.5 NDS 73.5 to mAP 71.8 NDS 73.6 to mAP 72.2 NDS 74.4?
So can I ask what's the main change for paper from v1 to v3?

**Comment by hht1996ok** [comment]
Thank you for your attention! We have modified the bug in the parameter transfer part of the code, and increased the number of parameters in the model, so that it can get better accuracy. However, due to time constraints, we only modified the code and experimented with it in BEVFusion[10], while BEVFusion[31] still uses the results of the previous version.

**Comment by AndyYuan96** [comment]
get，can I ask what do you mean that increase the number of parameters in the model，like double feature channel like deepinteraction or others，thanks。

**Comment by hht1996ok** [comment]
We modified the structure of the middle layer of LSS module to make the model more accurate. In EALSS-large, we have also increased the depth and number of channels for transfusion-L.

**Comment by ldtho** [comment]
Hi @hht1996ok can you elaborate a bit more? when you increase the model parameters, did you have to re-train the lidar brand?
